baseURL = "http://firantlabs.com/"
languageCode = "en-us"
title = "FireAnt Labs"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Posts about exploit development, red team, pentest and other random technology topics."

  # Metadata mostly used in document's head
  description = "Posts about exploit development, red team, pentest and other random technology topics."
  keywords = "security pentest pentesting redteam exploit development shellcode"
  images = [""]

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


[languages]
  [languages.en]
    title = "FireAnt Labs"
    subtitle = "Posts about exploit development, red team, pentest and other random technology topics."
    keywords = "security pentest pentesting redteam exploit development shellcode"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
    readMore = "Continue reading"

    [languages.en.params.logo]
      logoText = "cd ~"
      logoHomeLink = "/"
      logoMark = "fireantlabs$"
      logoCursorColor = "grey"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
#  [[menu.main]]
#    identifier = "blog"
#    name       = "Blog"
#    url        = "/posts"